### ISSUE TITLE
Build with CMake?

### ISSUE THREAD

**Issue by sholsapp** [mrtazz/restclient-cpp#41]
Would you merge a change that adds CMake support? I'm having a pretty evil time using this project in my CMake-based project.

**Comment by mrtazz** [comment]
I don't want to have to maintain two build systems in here, so unfortunately I don't think this would be a good addition. But I'm curious to what the problem is, as in my (very limited) experience with CMake building autotools projects as an [External Project](https://cmake.org/cmake/help/v2.8.8/cmake.html#module%3aExternalProject) seems to be the way to go. If there is anything in this project's build setup that is preventing that, then I'd be all up for fixing it of course.

**Comment by sholsapp** [comment]
I tried building it as an External Project and gave up after an hour or so. I can keep trying. If you have an examples, it would be nice to add them to the documentation.

**Comment by jeanpaullm** [comment]
did you succeed?, im new to Cmake and i'm having a hard time including this library into my project, i also tried finding the restclient-cpp/restclient.h to copy it into my root but i couldn't find it
